### ISSUE TITLE
any pretrained weight?

### ISSUE THREAD

**Issue by LeeKyungwook** [sunyiyou/SAFAS#1]
Thanks for sharing great work!

Could you share pretrained weights to reproduce thr performance?

**Comment by sunyiyou** [comment]
Hi, thanks for your interest! 

Since the dataset is not large, the training for each protocol should be easily finished in around 1 hour. 

I may release the pre-trained weight after mid-May upon finishing another NeurIPS submission.

**Comment by mlourencoeb** [comment]
Any news on the pre-trained model? It would be great to include it on our upcoming paper.

**Comment by tangwudu** [comment]
Is it possible to provide pre-trained weights?

**Comment by sunyiyou** [comment]
Hi Tang, you can access the models here. https://www.dropbox.com/scl/fi/13qqlqt78gsnvpx9kww04/SAFAS_trained.zip?rlkey=kdppzwf3i84aw8uxiokr4s869&dl=0

**Comment by tangwudu** [comment]
Thank you
