### ISSUE TITLE
Can you share your training log?

### ISSUE THREAD

**Issue by yaojunr** [sunyiyou/SAFAS#10]
Hello, I want to implement your method on my customized dataset, but I have met a problem, which shows my supcon loss is fluctuate in the range of (6, 7) and my model's domain generation perfomance seems poor.
Can you share your training log?

**Comment by sunyiyou** [comment]
[log_ICM-O.txt](https://github.com/sunyiyou/SAFAS/files/11453514/log_ICM-O.txt)
Hope this may be helpful.
