### ISSUE TITLE
question about betas

### ISSUE THREAD

**Issue by DanilKonon** [sunyiyou/SAFAS#11]
Hi! As I understand for each domain you train seperate beta classifier. But why can't we just train one classifier for all domains with ERM?

**Comment by sunyiyou** [comment]
Hi, the difference between IRM and ERM is the constraint in Eq.(4). A sufficient condition for the constraints in Eq. (4) to hold is that the live/spoof in each domain has the same direction. However, IRM is hard to optimize. We thus propose a PG-IRM algorithm that uses multiple classifiers to achieve the goal.
