### ISSUE TITLE
Incorrect implementaion of `NormedLogisticRegression` 

### ISSUE THREAD

**Issue by Leminhbinh0209** [sunyiyou/SAFAS#12]
The implementation of  `NormedLogisticRegression ` in the Resnet is incorrect at `F.normalize(self.weight, dim=0)`. If we do so weight's will only in `{-1,1}`. So, I think the correct one should be  `F.normalize(self.weight, dim=1)`.

**Comment by sunyiyou** [comment]
Thanks for pointing out! By default, we did not use the normalizedLR, the args.normfc is set to False.
