### ISSUE TITLE
why RandomResizedCrop during training?

### ISSUE THREAD

**Issue by tangwudu** [sunyiyou/SAFAS#14]
Hi, thanks for your work. But I have a question regarding RandomResizedCrop this function.
After preprocessing, we will have face cropped image. For example this one:
![image](https://github.com/sunyiyou/SAFAS/assets/3677630/6a3e9024-3c7c-4c74-9e6a-f70edd1922d4)

After RandomResizedCrop, we may get:
![image](https://github.com/sunyiyou/SAFAS/assets/3677630/48df3b10-dc45-461d-8dd2-eafd91f95678)

My question is that: instead of using full face image, why do we only use partial of the face? If we use partial of the face in training, how can we use it in production?

**Comment by sunyiyou** [comment]
Hi, this is the augmentation strategy used in training, so that the model do not overfit the training data. In the test time, you can use the full face.
