### ISSUE TITLE
How can we utilize the score output by an SAFAS model to determine whether a face image is live or spoof?

### ISSUE THREAD

**Issue by JohnCarpenter2** [sunyiyou/SAFAS#19]
Hi, we would like to use SAFAS to determine whether a face image is live or spoof. If we input the image into the SAFAS model, we can obtain a score output by the model. How can we utilize this score to determine whether the face image is live or spoof?
Thank you.

**Comment by sunyiyou** [comment]
If the final output layer uses the logistic function, then you can use 0.5 as a threshold. If the final layer is the softmax with two classes, you can compare two scores to see which one is higher.
