### ISSUE TITLE
Question about Training SAFAS on Custom Datasets with Different Domains

### ISSUE THREAD

**Issue by Nurmukhammeds** [sunyiyou/SAFAS#21]
Hi,

I've read your paper on the SAFAS approach, thank you for a Great Job.  Question regarding training the model on custom datasets. My custom datasets consist of a few different domain datasets, with some of them obtained from various environments (not homogeneous conditions, such as different resolutions, illuminations, devices, qualities).

Is it correct to pass such diverse domains to the model training for Separability learning, or should the datasets be collected under the same conditions to ensure proper training?

**Comment by sunyiyou** [comment]
Hi there. Thanks for your interest. 

If the images are collected under different resolutions, illuminations, devices, qualities, they should be considered as different domains. The separability learning makes sure that these domains can be well separated in the first place. 

If you hope your model can be generalizeable to more unseen domains, you should consider collecting domains as much as possible.

**Comment by Nurmukhammeds** [comment]
thank you
