### ISSUE TITLE
how to install ffmpeg?

### ISSUE THREAD

**Issue by Cassiatora** [sunyiyou/SAFAS#4]
Hi, 
Thanks for the great work. I want to know how th install ffmpeg. I tried the 'pip install ffmpeg-python'. But there is an error.

 File "/data/home/scv7305/.conda/envs/ddpm/lib/python3.9/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

**Comment by sunyiyou** [comment]
Hi, I may not be able to help with the installation issue. But one thing you do to avoid installing it is by changing the output of checkrotation function and always letting it returns -1.

**Comment by Cassiatora** [comment]
thanks for your reply. I solved this problem by recreating the environment. Maybe there is a conflict in the package of the original environment.
