### ISSUE TITLE
about the prposess

### ISSUE THREAD

**Issue by Cassiatora** [sunyiyou/SAFAS#5]
Hi,
I run the preposess.py, but the image resolution I get is not 224*224. I don't know if this is correct.
like this:
![crop_0000](https://user-images.githubusercontent.com/58909848/232984583-9b54be8d-a259-4bd6-8284-0044e920d61b.jpg)

**Comment by Garsonjw** [comment]
I have the same question!

**Comment by sunyiyou** [comment]
It will be resized during training. 
https://github.com/sunyiyou/SAFAS/blob/master/train.py#L92
